[build-system]
    requires = ["hatchling", "uv-dynamic-versioning"]
    build-backend = "hatchling.build"

[project]
    name = "novastar-client"
    dynamic = ["version"]
    description = "Python client for NovaStar REST endpoints (Stations)"
    authors = [
        { name = "Jeff Gregory", email = "jeffrey.s.gregory@usace.army.mil" },
    ]
    license = "MIT"
    readme = "README.md"
    requires-python = ">=3.12"
    dependencies = ["requests>=2.31.0", "click", "pandas", "hecdss"]

[project.scripts]
    ns5acp = "novastar_client.cli.ns5acp:cli"

[tool.hatch.version]
    source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
    vcs = "git"
    style = "pep440"

[dependency-groups]
    dev = [
        "pytest>=7.0",
        "pytest-cov>=4.0",
        "mypy>=1.0",
        "ruff>=0.4.0",
        "pdoc>=16.0.0",
    ]
