"""Testing data types"""

from typing import Any, Dict

datatypes: Dict[str, Any] = {
    "apiVersion": {
        "apiVersionMajor": "1",
        "apiVersionMinor": "13",
        "apiVersionMicro": "1",
        "apiVersionModifier": "",
        "apiVersionDate": "2025-08-15",
        "apiVersionTime": "",
        "apiDotDelimitedVersion": "1.13.1",
    },
    "attributionAndUsage": {
        "providerOrganizationText": "",
        "providerOrganizationUri": "",
        "dataPolicyUri": "",
        "disclaimerText": "",
        "disclaimerUri": "",
        "licenseText": "",
        "licenseUri": "",
        "usageConstraintsText": "",
        "usageConstraintsUri": "",
        "recommendedAttributionText": "",
    },
    "responseInfo": {
        "urlOriginal": "http://panama-cloud-ns5.trilynx-novastar.systems/novastar-data/api/v1/dataTypes?debug=False&format=json&sort=-name&shefPhysicalElement=H*",
        "urlOriginalEncoded": "http://panama-cloud-ns5.trilynx-novastar.systems/novastar-data/api/v1/dataTypes?debug=False&format=json&sort=-name&shefPhysicalElement=H%2A",
        "url": "http://localhost/novastar-data/api/v1/dataTypes?debug=False&format=json&sort=-name&shefPhysicalElement=H*",
        "urlEncoded": "http://localhost/novastar-data/api/v1/dataTypes?debug=False&format=json&sort=-name&shefPhysicalElement=H%2A",
        "periodStart": None,
        "periodEnd": None,
        "size": 25,
        "queryStart": "2026-05-01T10:08:55.965081-05:00",
        "queryMs": 0,
        "queryTargetMs": -999,
        "queryTargetMet": None,
        "isCached": False,
        "cacheExpirationTime": None,
    },
    "dataTypes": [
        {
            "name": "WaterLevelRiverMin",
            "displayName": "Height, Minimum River Stage",
            "description": "The minimum elevation of the water surface at a specified station above some arbitrary zero datum for the day.This translates to HGIRZNZ.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HN",
        },
        {
            "name": "WaterLevelRiverMax",
            "displayName": "Height, Maximum River Stage",
            "description": "The maximum elevation of the water surface at a specified station above some arbitrary zero datum for the day.This translates to HGIRZXZ.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HX",
        },
        {
            "name": "WaterLevelRiver7AM",
            "displayName": "Height, River Stage at 7AM",
            "description": "The elevation of the water surface at a specified station above some arbitrary zero datum at 7 AM local time just prior to the date-time stamp.This is translated to HGIRZZZ.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": False,
            "isValidError": "Custom data type name must be only alphabetic characters.",
            "shefPhysicalElement": "HY",
        },
        {
            "name": "WaterLevelRiver",
            "displayName": "Height, River Stage",
            "description": "The elevation of the water surface at a specified station above some arbitrary zero datum.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": True,
            "isValid": True,
            "shefPhysicalElement": "HG",
        },
        {
            "name": "WaterLevelPool",
            "displayName": "Elevation, Pool",
            "description": "The elevation of the impoundment not necessarily observed immediately above a dam or hydrolectric plant intake structure.  The term is usually expressed in MSL.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HP",
        },
        {
            "name": "WaterLevelNatLake",
            "displayName": "Height, Natural Lake",
            "description": "The elevation of the water surface in MSL of a lake having no man-made outlet.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HL",
        },
        {
            "name": "WaterLevelLake",
            "displayName": "Height, Lake Above a Specified Pool",
            "description": "The elevation of the water surface at a specified station above some arbitrary zero datum.  This elevation is usually not MSL.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": True,
            "isValid": True,
            "shefPhysicalElement": "HK",
        },
        {
            "name": "StageTrend",
            "displayName": "Stage Trend Indicator",
            "description": "Such as rising, falling, and stationary.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HI",
        },
        {
            "name": "StageCautionary",
            "displayName": "Stage, Cautionary",
            "description": "Height that may require action by local officials.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HU",
        },
        {
            "name": "HeightTide",
            "displayName": "Height, Tide",
            "description": "The periodic height of water resulting from gravitational interactions between the sun, moon, and earth.  'MLLW' is defined as the Mean Lower Low Water.  It is the mean of the lower low water heights in a mixed tide observed over a specific 19-year Metonic cycle.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HM",
        },
        {
            "name": "HeightSpillwayGate",
            "displayName": "Height, Spillway Gate",
            "description": "Height of spillway gate opening above spillway crest.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HJ",
        },
        {
            "name": "HeightRegulatingGate",
            "displayName": "Height, Regulating Gate",
            "description": "The height of a regulating gate opening.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HE",
        },
        {
            "name": "HeightOfReadingMSL",
            "displayName": "Height, of Reading (MSL)",
            "description": "The elevation above MSL at which an observation is taken.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": True,
            "isValid": True,
            "shefPhysicalElement": "HH",
        },
        {
            "name": "HeightOfReading",
            "displayName": "Height of Reading",
            "description": "The vertical or perpendicular elevation of an observation above a given datum.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": True,
            "isValid": True,
            "shefPhysicalElement": "HA",
        },
        {
            "name": "HeightHead",
            "displayName": "Height, Head",
            "description": "The amount of energy per pound of fluid.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": True,
            "isValid": True,
            "shefPhysicalElement": "HD",
        },
        {
            "name": "HeightFloodStage",
            "displayName": "Height, Flood Stage",
            "description": "",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HO",
        },
        {
            "name": "HeightCeiling",
            "displayName": "Height, Ceiling",
            "description": "The height ascribed to the lowest layer of clouds or obscuring phenomena when it is reported as broken, overcast, or obscuration and not classified 'thin' or 'partial'.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HC",
        },
        {
            "name": "ElevSpillwayTailwater",
            "displayName": "Height, Spillway Tailwater",
            "description": "The invert (lowest) elevation of a spillway.  This elevation is usually expressed in MSL.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HW",
        },
        {
            "name": "ElevSpillwayForebay",
            "displayName": "Elevation, Spillway Forebay",
            "description": "Spillway crest elevation usually expressed in MSL.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HS",
        },
        {
            "name": "ElevRuleCurve",
            "displayName": "Elevation, Rule Curve",
            "description": "The elevation of a reservoir from an operation under specified conditions to obtain best or predetermined results.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HR",
        },
        {
            "name": "ElevProjectTailwater",
            "displayName": "Elevation, Project Tailwater Stage",
            "description": "The elevation of the water surface immediately downstream from a dam or hydroelectric power plant.  This elevation is usually expressed in MSL.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HT",
        },
        {
            "name": "ElevFreezingLevel",
            "displayName": "Elevation, Freezing Level",
            "description": "The lower altitude in the atmosphere, over a given location, at which the air temperature is 32 degrees Fahrenheit or 0 degrees Celcius.The value is usually expressed relative to MSL.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HZ",
        },
        {
            "name": "DistDatumToRiverLevel",
            "displayName": "Distance from Datum to River Level",
            "description": "Used to estimate stage (see SHEF section 7.4.6).",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HQ",
        },
        {
            "name": "DepthSurfaceWater",
            "displayName": "Depth, Surface Water",
            "description": "The depth of water on a surface.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": False,
            "isValid": True,
            "shefPhysicalElement": "HV",
        },
        {
            "name": "DepthOfReading",
            "displayName": "Depth of Reading",
            "description": "The vertical or perpendicular elevation of an observation below a given datum.  This can include the depth to the water table or groundwater.",
            "dataTypeSourceType": "SHEF",
            "includeInOperatorStationSummary": True,
            "isValid": True,
            "shefPhysicalElement": "HB",
        },
    ],
}
