"""Testing Payloads"""

from typing import Dict


tscatalog_bare: Dict[str, list] = {
    "tscatalog": [
        {
            "locId": "1",
            "dataType": "NOSHEFCODE",
            "statisticType": None,
            "dataInterval": "NOSHEFCODE",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "ScaledValue",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": False,
            "problems": "SHEF parameter code is not set - unable to determine data type from SHEF physical element. SHEF parameter code is not set - unable to determine data interval from SHEF duration. Missing data units (check scaled value time series point type units). SHEF parameter code is missing.  Check point type SHEF parameter code.",
            "timeSeriesIdentifier": "1.NovaStar5.NOSHEFCODE.NOSHEFCODE",
        },
        {
            "locId": "1",
            "dataType": "Precip",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "",
            "timeSeriesValueSourceType": "RatedValue",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "PP",
            "shefPhysicalElement": "PP",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units.",
            "timeSeriesIdentifier": "1.NovaStar5.Precip.IrregSecond",
        },
        {
            "locId": "1",
            "dataType": "Precip",
            "statisticType": None,
            "dataInterval": "Year",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "RatedValue",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "PPY",
            "shefPhysicalElement": "PP",
            "shefDuration": "Y",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units.",
            "timeSeriesIdentifier": "1.NovaStar5.Precip.Year",
        },
        {
            "locId": "1",
            "dataType": "Precip-Rating",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "",
            "timeSeriesValueSourceType": "Rating",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "PP",
            "shefPhysicalElement": "PP",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Rating.IrregSecond",
        },
        {
            "locId": "1",
            "dataType": "Precip-Rating",
            "statisticType": None,
            "dataInterval": "Year",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "Rating",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "PPY",
            "shefPhysicalElement": "PP",
            "shefDuration": "Y",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Rating.Year",
        },
        {
            "locId": "1",
            "dataType": "Precip-Total",
            "statisticType": "Total",
            "dataInterval": "5Minute",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "IntervalCalc",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units (check interval input time series units).",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Total.5Minute",
        },
        {
            "locId": "1",
            "dataType": "Precip-Total",
            "statisticType": "Total",
            "dataInterval": "15Minute",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "IntervalCalc",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units (check interval input time series units).",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Total.15Minute",
        },
        {
            "locId": "1",
            "dataType": "Precip-Total",
            "statisticType": "Total",
            "dataInterval": "1Hour",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "IntervalCalc",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units (check interval input time series units).",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Total.1Hour",
        },
        {
            "locId": "1",
            "dataType": "Precip-Total",
            "statisticType": "Total",
            "dataInterval": "1Day",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "IntervalCalc",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units (check interval input time series units).",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Total.1Day",
        },
        {
            "locId": "1",
            "dataType": "Precip-Total",
            "statisticType": "Total",
            "dataInterval": "1Month",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "IntervalCalc",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units (check interval input time series units).",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Total.1Month",
        },
        {
            "locId": "1",
            "dataType": "Precip-Total",
            "statisticType": "Total",
            "dataInterval": "1Year",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "IntervalCalc",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units (check interval input time series units).",
            "timeSeriesIdentifier": "1.NovaStar5.Precip-Total.1Year",
        },
        {
            "locId": "1",
            "dataType": "PrecipAccum",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "mm",
            "timeSeriesValueSourceType": "ScaledValue",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1447,
            "pointNumId": 112,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "TB",
            "pointOutOfService": False,
            "pointRated": False,
            "pointTagName": "112",
            "pointTypeName": "Precipitation in ALERT2",
            "pointTypeDescription": "Precipitation en protocolo ALERT2",
            "pointTypeShefParameterCode": "PC",
            "pointTypeShortName": "precip",
            "pointTypeUnitsAbbreviated": "mm",
            "pointClassDescription": "Counter with rollover",
            "pointClassName": "counter",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "PC",
            "shefPhysicalElement": "PC",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipAccum.IrregSecond",
        },
        {
            "locId": "1",
            "dataType": "PrecipAccum-Calibration",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "",
            "timeSeriesValueSourceType": "Calibration",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1447,
            "pointNumId": 112,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "TB",
            "pointOutOfService": False,
            "pointRated": False,
            "pointTagName": "112",
            "pointTypeName": "Precipitation in ALERT2",
            "pointTypeDescription": "Precipitation en protocolo ALERT2",
            "pointTypeShefParameterCode": "PC",
            "pointTypeShortName": "precip",
            "pointTypeUnitsAbbreviated": "mm",
            "pointClassDescription": "Counter with rollover",
            "pointClassName": "counter",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "PC",
            "shefPhysicalElement": "PC",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipAccum-Calibration.IrregSecond",
        },
        {
            "locId": "1",
            "dataType": "PrecipAccum-NovaScore",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "",
            "timeSeriesValueSourceType": "NovaScore",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1447,
            "pointNumId": 112,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "TB",
            "pointOutOfService": False,
            "pointRated": False,
            "pointTagName": "112",
            "pointTypeName": "Precipitation in ALERT2",
            "pointTypeDescription": "Precipitation en protocolo ALERT2",
            "pointTypeShefParameterCode": "PC",
            "pointTypeShortName": "precip",
            "pointTypeUnitsAbbreviated": "mm",
            "pointClassDescription": "Counter with rollover",
            "pointClassName": "counter",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipAccum-NovaScore.IrregSecond",
        },
        {
            "locId": "1",
            "dataType": "PrecipAccum-NovaScore-Max",
            "statisticType": "Max",
            "dataInterval": "15Minute",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "NovaScore",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1447,
            "pointNumId": 112,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "TB",
            "pointOutOfService": False,
            "pointRated": False,
            "pointTagName": "112",
            "pointTypeName": "Precipitation in ALERT2",
            "pointTypeDescription": "Precipitation en protocolo ALERT2",
            "pointTypeShefParameterCode": "PC",
            "pointTypeShortName": "precip",
            "pointTypeUnitsAbbreviated": "mm",
            "pointClassDescription": "Counter with rollover",
            "pointClassName": "counter",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipAccum-NovaScore-Max.15Minute",
        },
        {
            "locId": "1",
            "dataType": "PrecipAccum-NovaScore-Max",
            "statisticType": "Max",
            "dataInterval": "1Hour",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "NovaScore",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1447,
            "pointNumId": 112,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "TB",
            "pointOutOfService": False,
            "pointRated": False,
            "pointTagName": "112",
            "pointTypeName": "Precipitation in ALERT2",
            "pointTypeDescription": "Precipitation en protocolo ALERT2",
            "pointTypeShefParameterCode": "PC",
            "pointTypeShortName": "precip",
            "pointTypeUnitsAbbreviated": "mm",
            "pointClassDescription": "Counter with rollover",
            "pointClassName": "counter",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipAccum-NovaScore-Max.1Hour",
        },
        {
            "locId": "1",
            "dataType": "PrecipAccum-NovaScore-Max",
            "statisticType": "Max",
            "dataInterval": "1Day",
            "isInstantaneous": False,
            "dataUnits": "",
            "timeSeriesValueSourceType": "NovaScore",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1447,
            "pointNumId": 112,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "TB",
            "pointOutOfService": False,
            "pointRated": False,
            "pointTagName": "112",
            "pointTypeName": "Precipitation in ALERT2",
            "pointTypeDescription": "Precipitation en protocolo ALERT2",
            "pointTypeShefParameterCode": "PC",
            "pointTypeShortName": "precip",
            "pointTypeUnitsAbbreviated": "mm",
            "pointClassDescription": "Counter with rollover",
            "pointClassName": "counter",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipAccum-NovaScore-Max.1Day",
        },
        {
            "locId": "1",
            "dataType": "PrecipAccum-Raw",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "",
            "timeSeriesValueSourceType": "RawValue",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1447,
            "pointNumId": 112,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "TB",
            "pointOutOfService": False,
            "pointRated": False,
            "pointTagName": "112",
            "pointTypeName": "Precipitation in ALERT2",
            "pointTypeDescription": "Precipitation en protocolo ALERT2",
            "pointTypeShefParameterCode": "PC",
            "pointTypeShortName": "precip",
            "pointTypeUnitsAbbreviated": "mm",
            "pointClassDescription": "Counter with rollover",
            "pointClassName": "counter",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "",
            "shefPhysicalElement": "",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipAccum-Raw.IrregSecond",
        },
        {
            "locId": "1",
            "dataType": "PrecipStormTotal",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "",
            "timeSeriesValueSourceType": "RatedValue",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "CP",
            "shefPhysicalElement": "CP",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "Missing data units.",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipStormTotal.IrregSecond",
        },
        {
            "locId": "1",
            "dataType": "PrecipStormTotal-Rating",
            "statisticType": None,
            "dataInterval": "IrregSecond",
            "isInstantaneous": True,
            "dataUnits": "",
            "timeSeriesValueSourceType": "Rating",
            "timeSeriesValueSourceIsEquation": False,
            "timeSeriesValueSourceIsForecast": False,
            "stationNumId": 1,
            "stationName": "AAA ESTACION DE PRUEBA",
            "stationDescription": 'Estacion Campbell  "DE PRUEBA" instalada el 9 de abril del 2019, consiste de un TB y un logger alimentado de energia solar ademas sensor de viento',
            "stationElevation": 95,
            "stationId": 226,
            "stationLatitude": 9.211,
            "stationLongitude": -79.917,
            "stationOutOfService": False,
            "stationRemoteTag": "1",
            "stationTagName": "TESTCAMP",
            "stationTypeDescription": "Campbell Scientific ALERT205 CR310 based ALERT2 transmitter",
            "stationTypeName": "Campbell Scientific ALERT2 Radio",
            "stationTypeProtocol": "ALERT2",
            "pointId": 1446,
            "pointNumId": 191,
            "pointName": "AAA ESTACION DE PRUEBA",
            "pointDescription": "",
            "pointOutOfService": False,
            "pointRated": True,
            "pointTagName": "191",
            "pointTypeName": "GPS Sync Campbell Scientific ALERT2",
            "pointTypeDescription": "GPS sync status for ALERT2 radio stations",
            "pointTypeShefParameterCode": "",
            "pointTypeShortName": "",
            "pointTypeUnitsAbbreviated": "",
            "pointClassDescription": "Digital value, usually no processing required",
            "pointClassName": "Digital",
            "ratingAssignShefParameterCode": "",
            "ratingTableOutUnitsAbbrev": "",
            "shefParameterCode": "CP",
            "shefPhysicalElement": "CP",
            "shefDuration": "",
            "shefType": "",
            "shefSource": "",
            "shefExtremum": "",
            "shefProbability": "",
            "isValid": True,
            "problems": "",
            "timeSeriesIdentifier": "1.NovaStar5.PrecipStormTotal-Rating.IrregSecond",
        },
    ]
}
