name: "Publish release to PyPI"

on:
  # push:
    # tags:
    #   # Publish on version tags, e.g. v0.1.0
    #   - "v[0-9]+.[0-9]+.[0-9]+"
    #   - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
    #   - "v[0-9]+.[0-9]+.[0-9]+[ab][0-9]+"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: actions/checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          ignore-empty-workdir: true

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: false

      - name: Build
        run: uv build --no-sources

      # Optional, but recommended: smoke-test the built artifacts.
      # Requires a tests/smoke_test.py that imports your package.
      # - name: Smoke test (wheel)
      #   run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      # - name: Smoke test (source distribution)
      #   run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py

      - name: actions/upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/novastar-client
    permissions:
      id-token: write # required for Trusted Publishing (OIDC) — no secrets needed
      contents: read # for actions/checkout, if you're in a private repo
    steps:
      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: false

      - name: actions/download-artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist
          path: dist/

      - name: astral-sh/attest-action
        uses: astral-sh/attest-action@v0.0.6

      - name: Publish to PyPI
        run: uv publish
